// GENERATED by scripts/gen-spec.mjs from spec/*.json - do not edit by hand.
// Run `npm run gen:spec` after changing the JSON.

import type { DawCcMapSpec, PaletteSpec } from './types.ts';

export const DAW_CC_MAP = {
  "source": "Novation Launch Control XL 3 Programmer's Reference Guide v1.0, p.9-10, p.17",
  "verified": "against official documentation; NOT yet against hardware capture",
  "notes": {
    "ledAddressing": "The same control index is used to colour that control's LED: B0h <index> <palette 0-127>. The official guide specifies channel 1 (B0h). Captures of Ableton Live 12 show it also emitting BFh (channel 16) for some indices - accept both on input.",
    "touchEvents": "When enabled (CC 71 ch7), touch on/off is CC on channel 15 using the same control index, value 127 = on, 0 = off. Example: leftmost fader = BEh 05h 7Fh.",
    "shift": "Shift is on channel 7 because it is bound to feature control 3Fh (63).",
    "mode": "The Mode button emits nothing (n/a); it is a local UI button."
  },
  "channels": {
    "encodersAndFaders": 16,
    "buttons": 1,
    "shift": 7,
    "featureControls": 7,
    "featureControlQueries": 8,
    "touch": 15
  },
  "controls": {
    "faders": {
      "channel": 16,
      "cc": [
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12
      ]
    },
    "encoderRow1": {
      "channel": 16,
      "ccAbsolute": [
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20
      ],
      "ccRelative": [
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84
      ],
      "relativeToggleCC": 69
    },
    "encoderRow2": {
      "channel": 16,
      "ccAbsolute": [
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28
      ],
      "ccRelative": [
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92
      ],
      "relativeToggleCC": 72
    },
    "encoderRow3": {
      "channel": 16,
      "ccAbsolute": [
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36
      ],
      "ccRelative": [
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100
      ],
      "relativeToggleCC": 73
    },
    "buttonRowTop": {
      "channel": 1,
      "cc": [
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44
      ]
    },
    "buttonRowBottom": {
      "channel": 1,
      "cc": [
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52
      ]
    },
    "soloArm": {
      "channel": 1,
      "cc": 65
    },
    "muteSelect": {
      "channel": 1,
      "cc": 66
    },
    "utilitySmallButton": {
      "channel": 1,
      "cc": 104
    },
    "trackPrev": {
      "channel": 1,
      "cc": 103
    },
    "trackNext": {
      "channel": 1,
      "cc": 102
    },
    "pageUp": {
      "channel": 1,
      "cc": 106
    },
    "pageDown": {
      "channel": 1,
      "cc": 107
    },
    "record": {
      "channel": 1,
      "cc": 118
    },
    "play": {
      "channel": 1,
      "cc": 116
    },
    "shift": {
      "channel": 7,
      "cc": 63
    },
    "mode": {
      "channel": null,
      "cc": null
    }
  },
  "relativeEncoding": {
    "pivot": 64
  },
  "featureControls": {
    "30": {
      "name": "surfaceModeSelect",
      "flags": "#",
      "values": {
        "1": "DAW Mixer",
        "2": "DAW Control",
        "6-9": "Custom Modes 1-4",
        "18-29": "Custom Modes 5-16"
      }
    },
    "63": {
      "name": "shiftOnOff",
      "flags": "#"
    },
    "69": {
      "name": "encoderRow1Relative",
      "flags": "#"
    },
    "70": {
      "name": "faderPickup",
      "flags": "#"
    },
    "71": {
      "name": "touchEvents",
      "flags": "#"
    },
    "72": {
      "name": "encoderRow2Relative",
      "flags": "#"
    },
    "73": {
      "name": "encoderRow3Relative",
      "flags": "#"
    },
    "100": {
      "name": "globalMidiChannel",
      "flags": "*",
      "range": [
        0,
        15
      ]
    },
    "111": {
      "name": "ledBrightness",
      "flags": "*",
      "range": [
        0,
        127
      ]
    },
    "112": {
      "name": "screenBrightness",
      "flags": "*",
      "range": [
        0,
        127
      ]
    },
    "113": {
      "name": "temporaryDisplayTimeout",
      "flags": "*",
      "range": [
        0,
        99
      ],
      "units": "tenths of a second, minimum 1 second at 0"
    },
    "120": {
      "name": "out2MidiThru",
      "flags": "*"
    },
    "121": {
      "name": "encoderCurve",
      "flags": "*",
      "values": {
        "0": "slow",
        "1": "medium",
        "2": "fast"
      }
    }
  },
  "sysex": {
    "header": [
      240,
      0,
      32,
      41,
      2,
      21
    ],
    "headerHex": "F0 00 20 29 02 15",
    "commands": {
      "0x01_0x53": "set RGB colour: F0 00 20 29 02 15 01 53 <index> <R> <G> <B> F7",
      "0x02": "DAW mode: 02 7F = enable, 02 00 = disable (device echoes)",
      "0x04": "configure display: 04 <target> <config> F7",
      "0x06": "set display text: 06 <target> <field> <ascii...> F7",
      "0x09": "bitmap: 09 <target> <1216 bytes> F7; device replies F0 00 20 29 02 15 09 7F"
    },
    "noteAliases": {
      "enableDawMode": [
        159,
        12,
        127
      ],
      "disableDawMode": [
        159,
        12,
        0
      ],
      "enableFeatureControls": [
        159,
        11,
        127
      ],
      "disableFeatureControls": [
        159,
        11,
        0
      ]
    }
  },
  "displayTargets": {
    "32": "bitmap: stationary display",
    "33": "bitmap: global temporary display",
    "53": "permanent / stationary display",
    "54": "overlay / temporary display",
    "5-12": "temporary display for faders",
    "13-36": "temporary display for encoders"
  },
  "displayArrangements": {
    "0": "cancel display",
    "1": "2 lines: parameter name + text value (2 fields)",
    "2": "3 lines: title, parameter name, text value (3 fields)",
    "3": "1 line + 2x4: title and 8 names (9 fields)",
    "4": "2 lines: parameter name + numeric value (default, 1 field)",
    "31": "trigger display with current contents"
  }
} as const satisfies DawCcMapSpec;

export const PALETTE = [
  {
    "index": 0,
    "hex": "#616161",
    "rgb": [
      97,
      97,
      97
    ]
  },
  {
    "index": 1,
    "hex": "#B3B3B3",
    "rgb": [
      179,
      179,
      179
    ]
  },
  {
    "index": 2,
    "hex": "#DDDDDD",
    "rgb": [
      221,
      221,
      221
    ]
  },
  {
    "index": 3,
    "hex": "#FFFFFF",
    "rgb": [
      255,
      255,
      255
    ]
  },
  {
    "index": 4,
    "hex": "#FFB3B3",
    "rgb": [
      255,
      179,
      179
    ]
  },
  {
    "index": 5,
    "hex": "#FF6161",
    "rgb": [
      255,
      97,
      97
    ]
  },
  {
    "index": 6,
    "hex": "#DD6161",
    "rgb": [
      221,
      97,
      97
    ]
  },
  {
    "index": 7,
    "hex": "#B36161",
    "rgb": [
      179,
      97,
      97
    ]
  },
  {
    "index": 8,
    "hex": "#FFF3D5",
    "rgb": [
      255,
      243,
      213
    ]
  },
  {
    "index": 9,
    "hex": "#FFB361",
    "rgb": [
      255,
      179,
      97
    ]
  },
  {
    "index": 10,
    "hex": "#DD8C61",
    "rgb": [
      221,
      140,
      97
    ]
  },
  {
    "index": 11,
    "hex": "#B37661",
    "rgb": [
      179,
      118,
      97
    ]
  },
  {
    "index": 12,
    "hex": "#FFEEA1",
    "rgb": [
      255,
      238,
      161
    ]
  },
  {
    "index": 13,
    "hex": "#FFFF61",
    "rgb": [
      255,
      255,
      97
    ]
  },
  {
    "index": 14,
    "hex": "#DDDD61",
    "rgb": [
      221,
      221,
      97
    ]
  },
  {
    "index": 15,
    "hex": "#B3B361",
    "rgb": [
      179,
      179,
      97
    ]
  },
  {
    "index": 16,
    "hex": "#DDFFA1",
    "rgb": [
      221,
      255,
      161
    ]
  },
  {
    "index": 17,
    "hex": "#C2FF61",
    "rgb": [
      194,
      255,
      97
    ]
  },
  {
    "index": 18,
    "hex": "#A1DD61",
    "rgb": [
      161,
      221,
      97
    ]
  },
  {
    "index": 19,
    "hex": "#81B361",
    "rgb": [
      129,
      179,
      97
    ]
  },
  {
    "index": 20,
    "hex": "#C2FFB3",
    "rgb": [
      194,
      255,
      179
    ]
  },
  {
    "index": 21,
    "hex": "#61FF61",
    "rgb": [
      97,
      255,
      97
    ]
  },
  {
    "index": 22,
    "hex": "#61DD61",
    "rgb": [
      97,
      221,
      97
    ]
  },
  {
    "index": 23,
    "hex": "#61B361",
    "rgb": [
      97,
      179,
      97
    ]
  },
  {
    "index": 24,
    "hex": "#C2FFC2",
    "rgb": [
      194,
      255,
      194
    ]
  },
  {
    "index": 25,
    "hex": "#61FF8C",
    "rgb": [
      97,
      255,
      140
    ]
  },
  {
    "index": 26,
    "hex": "#61DD76",
    "rgb": [
      97,
      221,
      118
    ]
  },
  {
    "index": 27,
    "hex": "#61B36B",
    "rgb": [
      97,
      179,
      107
    ]
  },
  {
    "index": 28,
    "hex": "#C2FFCC",
    "rgb": [
      194,
      255,
      204
    ]
  },
  {
    "index": 29,
    "hex": "#61FFCC",
    "rgb": [
      97,
      255,
      204
    ]
  },
  {
    "index": 30,
    "hex": "#61DDA1",
    "rgb": [
      97,
      221,
      161
    ]
  },
  {
    "index": 31,
    "hex": "#61B381",
    "rgb": [
      97,
      179,
      129
    ]
  },
  {
    "index": 32,
    "hex": "#C2FFF3",
    "rgb": [
      194,
      255,
      243
    ]
  },
  {
    "index": 33,
    "hex": "#61FFE9",
    "rgb": [
      97,
      255,
      233
    ]
  },
  {
    "index": 34,
    "hex": "#61DDC2",
    "rgb": [
      97,
      221,
      194
    ]
  },
  {
    "index": 35,
    "hex": "#61B396",
    "rgb": [
      97,
      179,
      150
    ]
  },
  {
    "index": 36,
    "hex": "#C2F3FF",
    "rgb": [
      194,
      243,
      255
    ]
  },
  {
    "index": 37,
    "hex": "#61EEFF",
    "rgb": [
      97,
      238,
      255
    ]
  },
  {
    "index": 38,
    "hex": "#61C7DD",
    "rgb": [
      97,
      199,
      221
    ]
  },
  {
    "index": 39,
    "hex": "#61A1B3",
    "rgb": [
      97,
      161,
      179
    ]
  },
  {
    "index": 40,
    "hex": "#C2DDFF",
    "rgb": [
      194,
      221,
      255
    ]
  },
  {
    "index": 41,
    "hex": "#61C7FF",
    "rgb": [
      97,
      199,
      255
    ]
  },
  {
    "index": 42,
    "hex": "#61A1DD",
    "rgb": [
      97,
      161,
      221
    ]
  },
  {
    "index": 43,
    "hex": "#6181B3",
    "rgb": [
      97,
      129,
      179
    ]
  },
  {
    "index": 44,
    "hex": "#A18CFF",
    "rgb": [
      161,
      140,
      255
    ]
  },
  {
    "index": 45,
    "hex": "#6161FF",
    "rgb": [
      97,
      97,
      255
    ]
  },
  {
    "index": 46,
    "hex": "#6161DD",
    "rgb": [
      97,
      97,
      221
    ]
  },
  {
    "index": 47,
    "hex": "#6161B3",
    "rgb": [
      97,
      97,
      179
    ]
  },
  {
    "index": 48,
    "hex": "#CCB3FF",
    "rgb": [
      204,
      179,
      255
    ]
  },
  {
    "index": 49,
    "hex": "#A161FF",
    "rgb": [
      161,
      97,
      255
    ]
  },
  {
    "index": 50,
    "hex": "#8161DD",
    "rgb": [
      129,
      97,
      221
    ]
  },
  {
    "index": 51,
    "hex": "#7661B3",
    "rgb": [
      118,
      97,
      179
    ]
  },
  {
    "index": 52,
    "hex": "#FFB3FF",
    "rgb": [
      255,
      179,
      255
    ]
  },
  {
    "index": 53,
    "hex": "#FF61FF",
    "rgb": [
      255,
      97,
      255
    ]
  },
  {
    "index": 54,
    "hex": "#DD61DD",
    "rgb": [
      221,
      97,
      221
    ]
  },
  {
    "index": 55,
    "hex": "#B361B3",
    "rgb": [
      179,
      97,
      179
    ]
  },
  {
    "index": 56,
    "hex": "#FFB3D5",
    "rgb": [
      255,
      179,
      213
    ]
  },
  {
    "index": 57,
    "hex": "#FF61C2",
    "rgb": [
      255,
      97,
      194
    ]
  },
  {
    "index": 58,
    "hex": "#DD61A1",
    "rgb": [
      221,
      97,
      161
    ]
  },
  {
    "index": 59,
    "hex": "#B3618C",
    "rgb": [
      179,
      97,
      140
    ]
  },
  {
    "index": 60,
    "hex": "#FF7661",
    "rgb": [
      255,
      118,
      97
    ]
  },
  {
    "index": 61,
    "hex": "#E9B361",
    "rgb": [
      233,
      179,
      97
    ]
  },
  {
    "index": 62,
    "hex": "#DDC261",
    "rgb": [
      221,
      194,
      97
    ]
  },
  {
    "index": 63,
    "hex": "#A1A161",
    "rgb": [
      161,
      161,
      97
    ]
  },
  {
    "index": 64,
    "hex": "#61B361",
    "rgb": [
      97,
      179,
      97
    ]
  },
  {
    "index": 65,
    "hex": "#61B38C",
    "rgb": [
      97,
      179,
      140
    ]
  },
  {
    "index": 66,
    "hex": "#618CD5",
    "rgb": [
      97,
      140,
      213
    ]
  },
  {
    "index": 67,
    "hex": "#6161FF",
    "rgb": [
      97,
      97,
      255
    ]
  },
  {
    "index": 68,
    "hex": "#61B3B3",
    "rgb": [
      97,
      179,
      179
    ]
  },
  {
    "index": 69,
    "hex": "#8C61F3",
    "rgb": [
      140,
      97,
      243
    ]
  },
  {
    "index": 70,
    "hex": "#CCB3C2",
    "rgb": [
      204,
      179,
      194
    ]
  },
  {
    "index": 71,
    "hex": "#8C7681",
    "rgb": [
      140,
      118,
      129
    ]
  },
  {
    "index": 72,
    "hex": "#FF6161",
    "rgb": [
      255,
      97,
      97
    ]
  },
  {
    "index": 73,
    "hex": "#F3FFA1",
    "rgb": [
      243,
      255,
      161
    ]
  },
  {
    "index": 74,
    "hex": "#EEFC61",
    "rgb": [
      238,
      252,
      97
    ]
  },
  {
    "index": 75,
    "hex": "#CCFF61",
    "rgb": [
      204,
      255,
      97
    ]
  },
  {
    "index": 76,
    "hex": "#76DD61",
    "rgb": [
      118,
      221,
      97
    ]
  },
  {
    "index": 77,
    "hex": "#61FFCC",
    "rgb": [
      97,
      255,
      204
    ]
  },
  {
    "index": 78,
    "hex": "#61E9FF",
    "rgb": [
      97,
      233,
      255
    ]
  },
  {
    "index": 79,
    "hex": "#61A1FF",
    "rgb": [
      97,
      161,
      255
    ]
  },
  {
    "index": 80,
    "hex": "#8C61FF",
    "rgb": [
      140,
      97,
      255
    ]
  },
  {
    "index": 81,
    "hex": "#CC61FC",
    "rgb": [
      204,
      97,
      252
    ]
  },
  {
    "index": 82,
    "hex": "#EE8CDD",
    "rgb": [
      238,
      140,
      221
    ]
  },
  {
    "index": 83,
    "hex": "#A17661",
    "rgb": [
      161,
      118,
      97
    ]
  },
  {
    "index": 84,
    "hex": "#FFA161",
    "rgb": [
      255,
      161,
      97
    ]
  },
  {
    "index": 85,
    "hex": "#DDF961",
    "rgb": [
      221,
      249,
      97
    ]
  },
  {
    "index": 86,
    "hex": "#D5FF8C",
    "rgb": [
      213,
      255,
      140
    ]
  },
  {
    "index": 87,
    "hex": "#61FF61",
    "rgb": [
      97,
      255,
      97
    ]
  },
  {
    "index": 88,
    "hex": "#B3FFA1",
    "rgb": [
      179,
      255,
      161
    ]
  },
  {
    "index": 89,
    "hex": "#CCFCD5",
    "rgb": [
      204,
      252,
      213
    ]
  },
  {
    "index": 90,
    "hex": "#B3FFF6",
    "rgb": [
      179,
      255,
      246
    ]
  },
  {
    "index": 91,
    "hex": "#CCE4FF",
    "rgb": [
      204,
      228,
      255
    ]
  },
  {
    "index": 92,
    "hex": "#A1C2F6",
    "rgb": [
      161,
      194,
      246
    ]
  },
  {
    "index": 93,
    "hex": "#D5C2F9",
    "rgb": [
      213,
      194,
      249
    ]
  },
  {
    "index": 94,
    "hex": "#F98CFF",
    "rgb": [
      249,
      140,
      255
    ]
  },
  {
    "index": 95,
    "hex": "#FF61CC",
    "rgb": [
      255,
      97,
      204
    ]
  },
  {
    "index": 96,
    "hex": "#FFC261",
    "rgb": [
      255,
      194,
      97
    ]
  },
  {
    "index": 97,
    "hex": "#F3EE61",
    "rgb": [
      243,
      238,
      97
    ]
  },
  {
    "index": 98,
    "hex": "#E4FF61",
    "rgb": [
      228,
      255,
      97
    ]
  },
  {
    "index": 99,
    "hex": "#DDCC61",
    "rgb": [
      221,
      204,
      97
    ]
  },
  {
    "index": 100,
    "hex": "#B3A161",
    "rgb": [
      179,
      161,
      97
    ]
  },
  {
    "index": 101,
    "hex": "#61BA76",
    "rgb": [
      97,
      186,
      118
    ]
  },
  {
    "index": 102,
    "hex": "#76C28C",
    "rgb": [
      118,
      194,
      140
    ]
  },
  {
    "index": 103,
    "hex": "#8181A1",
    "rgb": [
      129,
      129,
      161
    ]
  },
  {
    "index": 104,
    "hex": "#818CCC",
    "rgb": [
      129,
      140,
      204
    ]
  },
  {
    "index": 105,
    "hex": "#CCAA81",
    "rgb": [
      204,
      170,
      129
    ]
  },
  {
    "index": 106,
    "hex": "#DD6161",
    "rgb": [
      221,
      97,
      97
    ]
  },
  {
    "index": 107,
    "hex": "#F9B3A1",
    "rgb": [
      249,
      179,
      161
    ]
  },
  {
    "index": 108,
    "hex": "#F9BA76",
    "rgb": [
      249,
      186,
      118
    ]
  },
  {
    "index": 109,
    "hex": "#FFF38C",
    "rgb": [
      255,
      243,
      140
    ]
  },
  {
    "index": 110,
    "hex": "#E9F9A1",
    "rgb": [
      233,
      249,
      161
    ]
  },
  {
    "index": 111,
    "hex": "#D5EE76",
    "rgb": [
      213,
      238,
      118
    ]
  },
  {
    "index": 112,
    "hex": "#8181A1",
    "rgb": [
      129,
      129,
      161
    ]
  },
  {
    "index": 113,
    "hex": "#F9F9D5",
    "rgb": [
      249,
      249,
      213
    ]
  },
  {
    "index": 114,
    "hex": "#DDFCE4",
    "rgb": [
      221,
      252,
      228
    ]
  },
  {
    "index": 115,
    "hex": "#E9E9FF",
    "rgb": [
      233,
      233,
      255
    ]
  },
  {
    "index": 116,
    "hex": "#E4D5FF",
    "rgb": [
      228,
      213,
      255
    ]
  },
  {
    "index": 117,
    "hex": "#B3B3B3",
    "rgb": [
      179,
      179,
      179
    ]
  },
  {
    "index": 118,
    "hex": "#D5D5D5",
    "rgb": [
      213,
      213,
      213
    ]
  },
  {
    "index": 119,
    "hex": "#F9FFFF",
    "rgb": [
      249,
      255,
      255
    ]
  },
  {
    "index": 120,
    "hex": "#E96161",
    "rgb": [
      233,
      97,
      97
    ]
  },
  {
    "index": 121,
    "hex": "#AA6161",
    "rgb": [
      170,
      97,
      97
    ]
  },
  {
    "index": 122,
    "hex": "#81F661",
    "rgb": [
      129,
      246,
      97
    ]
  },
  {
    "index": 123,
    "hex": "#61B361",
    "rgb": [
      97,
      179,
      97
    ]
  },
  {
    "index": 124,
    "hex": "#F3EE61",
    "rgb": [
      243,
      238,
      97
    ]
  },
  {
    "index": 125,
    "hex": "#B3A161",
    "rgb": [
      179,
      161,
      97
    ]
  },
  {
    "index": 126,
    "hex": "#EEC261",
    "rgb": [
      238,
      194,
      97
    ]
  },
  {
    "index": 127,
    "hex": "#C27661",
    "rgb": [
      194,
      118,
      97
    ]
  }
] as const satisfies PaletteSpec;
