#!/usr/bin/env node
/**
 * Turns the protocol JSON in `spec/` into typed constants in
 * `packages/core/src/spec/generated.ts`.
 *
 * Why generate rather than import: the panel runs in a browser and cannot read
 * files off disk, and `resolveJsonModule` can't reach outside the package root.
 * Emitting `satisfies` clauses also means tsc checks the JSON shape at build
 * time, which is the cheapest schema check available.
 *
 * Keys beginning with `$` are documentation for humans reading the JSON and are
 * stripped on the way through.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'packages/core/src/spec/generated.ts');

const stripDocKeys = (value) => {
  if (Array.isArray(value)) return value.map(stripDocKeys);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => !key.startsWith('$'))
      .map(([key, inner]) => [key, stripDocKeys(inner)]),
  );
};

const read = (name) => stripDocKeys(JSON.parse(readFileSync(join(root, 'spec', name), 'utf8')));

const ccMap = read('lcxl3-daw-cc-map.json');
const palette = read('lcxl3-palette.json');

if (palette.length !== 128) {
  throw new Error(`palette must have exactly 128 entries, found ${palette.length}`);
}
palette.forEach((entry, i) => {
  if (entry.index !== i) throw new Error(`palette entry ${i} has index ${entry.index}`);
  if (entry.rgb.length !== 3) throw new Error(`palette entry ${i} has ${entry.rgb.length} channels`);
});

const source = `// GENERATED by scripts/gen-spec.mjs from spec/*.json - do not edit by hand.
// Run \`npm run gen:spec\` after changing the JSON.

import type { DawCcMapSpec, PaletteSpec } from './types.ts';

export const DAW_CC_MAP = ${JSON.stringify(ccMap, null, 2)} as const satisfies DawCcMapSpec;

export const PALETTE = ${JSON.stringify(palette, null, 2)} as const satisfies PaletteSpec;
`;

writeFileSync(out, source);
console.log(`gen-spec: wrote ${out} (${palette.length} palette entries)`);
